query GetPagedEvents($datetime: String!, $limit: Int, $offset: Int, $type: String) {
  result: getEvents(datetime: $datetime, limit: $limit, offset: $offset, type: $type) {
    total
    items {
      aggregateId,
      dateTime,
      type,
      data,
      metadata
    }
  }
}

{
  "datetime": "2021-08-03",
  "limit": 10,
  "offset": 1,
  "search": ""
}

query GetEvents($id: String!) {
  result: getEventById(id: $id) {
      aggregateId,
      dateTime,
      type,
      data,
      metadata
  }
}

{
  "id": "4c2766a-2e3a-4519-947d-49d4982a724f"
}