query GetRequestLogs($datetime: String!, $limit: Int, $offset: Int, $search: String) {
  result: getLogs(datetime: $datetime, limit: $limit, offset: $offset, search: $search) {
    total
    itens {
      id
      datetime
      payload
    }
  }
}

variables {
  "datetime": "2019-12-31",
  "limit": 10,
  "offset": 0
}