query GetRequestLogs($datetime: String!, $limit: Int, $offset: Int, $search: String) {
  getRequestLogs(datetime: $datetime, limit: $limit, offset: $offset, search: $search) {
    id
    datetime
    userAgent
    identifier
    runtime
  }
}


query GetIntegrationsLog($datetime: String!, $limit: Int, $offset: Int) {
  getIntegrationsLog(datetime: $datetime, limit: $limit, offset: $offset) {
    id
    datetime,
    userId,
    runtime,
    dataSend,
    dataReceived
  }
}

variables {
  "datetime": "2019-12-31",
  "limit": 10,
  "offset": 0
}